# Tools
hhblits_tool: hhblits
rosetta_tool: utils/trRosetta/predict_many.py

# Database
uniclust_database: utils/hhblits/uniclust30_2018_08/uniclust30_2018_08

# Models
rosetta_model: utils/trRosetta/model2019_07
esm2_checkpoints: utils/esm2/

# Features encoding method JSON
esm2_representations_json : utils/esm2/esm2_representations.json
3D_structure_methods_json : utils/3D_structure_methods.json